use sakila;

#1. List the number of films per category.
select count(film.title), category.name from film 
join film_category using (film_id)
join category using (category_id)
group by category.name;

#2. Retrieve the store ID, city, and country for each store.
select store.store_id, city.city, country.country from store 
join address using (address_id)
join city using (city_id)
join country using (country_id);

#3. Calculate the total revenue generated by each store in dollars.
select sum(payment.amount) from store 
join staff using (store_id)
join payment using (staff_id);

#4. Determine the average running time of films for each category.
select avg(film.length) as "average_film_length", category.name as "category_name" from film 
join film_category using (film_id)
join category using (category_id)
group by category.name;

#5. Identify the film categories with the longest average running time.
select avg(film.length) as "average_film_length", category.name as "category_name" from film 
join film_category using (film_id)
join category using (category_id)
group by category.name
order by avg(film.length) desc
limit 6;

#6. Display the top 10 most frequently rented movies in descending order.
select film.title from film 
join inventory using (film_id)
join rental using (inventory_id)
group by film.title
order by count(rental.rental_id) desc
limit 10;

#7. Determine if "Academy Dinosaur" can be rented from Store 1.
select film.title, store_id from film
join inventory using (film_id)
join store using (store_id)
where film.title in ("Academy Dinosaur");

with stock as
(
select film.title, store.store_id, count(store.store_id) as copies from film
join inventory using (film_id)
join store using (store_id)
where film.title in ("Academy Dinosaur")
group by store.store_id
)
select store_id,
case when copies > 0 then "Yes"
else "No"
end as "is available"
from stock
where store_id = 1;
